### ISSUE TITLE
Loss of typing information on composed functions

### ISSUE THREAD

**Issue by muxator** [mentalisttraceur/python-compose#6]
Passing any function through `compose.compose()` seems to strip away all the information about the types of those functions.

Minimal example:

```python
import compose


def f(x: int) -> str:
    return f"{x}"


# compose f with the identity function
g = compose.compose(f)

reveal_type(f(1))
reveal_type(g(1))
```

Testing on python 3.11 yields:

```
$ mypy --version
mypy 1.5.1 (compiled: yes)

$ mypy test_compose.py 
test_compose.py:11: note: Revealed type is "builtins.str"
test_compose.py:12: note: Revealed type is "Any"
```

I expected that the static type checker would have printed `builtins.str` even for `g(1)`.

This is a stripped down example of a larger problem I had early on on a project of mine, where I wrongly assumed that composed functions would have brought over the type information about their signature. I ended up introducing a bug in my project because of this assumption.

This issue is a cross post of something I also found in another library (https://github.com/pytoolz/toolz/issues/569).

Is this a limitation of the libraries? Of the language itself? Or the static analyzers?

Thank you.

**Comment by mentalisttraceur** [comment]
It's partially a library limitation (duplicate of #5 as far as that goes; see also the stack overflow link from my comment in that issue), and partially a language+analyzer limitation - Python has been slow to add type hints for combining/modifying callables (some relevant discussion in https://github.com/pytoolz/toolz/issues/523 ), and then static analyzers have been slow to support those few hints that we do get (as you might've seen in https://github.com/python/mypy/issues/12280 ).

In particular, last I checked there was still no good way provided by Python to tell the static type checker that the return type of one function is supposed to be the same as the argument type of the next function in a variadic way. So `compose` type hints have to be hard-coded for each arity (number of composed functions).

I do apologize if the "can be type-checked" in my project description caused your assumption. When I wrote that, I was just talking about type-checking at runtime (i.e. `isinstance` checks to distinguish a `compose` instance from functions/lambdas), and I was able to convince myself that the misinterpretation potential was acceptably low because static type analysis wasn't yet so common in Python.

**Comment by mentalisttraceur** [comment]
Do you mind installing https://pypi.org/project/compose-stubs along with `compose` and letting me know if type-checking starts to work for you?

Just note the `0.*` version number and "alpha" development status classifier for now.

I've tested with MyPy and it works for `compose` (still working on the `async` variants), and for some typing mistakes the MyPy errors are even good - but when there's a mismatch between the return type of one composed function and the argument type of the next composed function, MyPy's error is the rather unhelpful "Cannot infer type of argument ..." instead of the more helpful "... incompatible type ...; expected ...".

**Comment by muxator** [comment]
I'll try it tomorrow, thanks!

**Comment by mentalisttraceur** [comment]
Stubs package is about as good as it's going to get, I think. I've bumped it up from alpha to beta, and If we don't notice any serious issues in the near future I'll promote it to stable v1.0.0 soon.

**Comment by mentalisttraceur** [comment]
> At this point, in compose's README, I'd suggest to mention the usefulness of also installing compose-stubs if one wants to have non-surprising static typing.

Yep! That was my plan, I was just delaying to see if we noticed any deal-breaking issues. Since we haven't, `compose-stubs` is promoted to a stable v1.0.0 release and `compose` v1.5.0 refers to the stubs package in the description/README.
